#!/bin/sh

# exit on any error
set -e

# get git directory path
dir="`git rev-parse --git-dir`"

# generate the ctag file
git ls-files | \
    ctags -L - -f"$dir/tags" \
        --recurse \
        --tag-relative \
        --languages=php \
        --PHP-kinds=+cf-v
